export const fonts = {
  Black: 'BeVietnamPro-Black',
  BlackItalic: 'BeVietnamPro-BlackItalic',
  Bold: 'BeVietnamPro-Bold',
  BoldItalic: 'BeVietnamPro-BoldItalic',
  ExtraBold: 'BeVietnamPro-ExtraBold',
  ExtraBoldItalic: 'BeVietnamPro-ExtraBoldItalic',
  ExtraLight: 'BeVietnamPro-ExtraLight',
  ExtraLightItalic: 'BeVietnamPro-ExtraLightItalic',
  Italic: 'BeVietnamPro-Italic',
  Light: 'BeVietnamPro-Light',
  LightItalic: 'BeVietnamPro-LightItalic',
  Medium: 'BeVietnamPro-Medium',
  MediumItalic: 'BeVietnamPro-MediumItalic',
  Regular: 'BeVietnamPro-Regular',
  SemiBold: 'BeVietnamPro-SemiBold',
  SemiBoldItalic: 'BeVietnamPro-SemiBoldItalic',
  Thin: 'BeVietnamPro-Thin',
  ThinItalic: 'BeVietnamPro-ThinItalic',
};
